apiVersion: v1
kind: Pod
metadata:
  name: iperf3-host-network-service
  labels:
    app: iperf3-host-network-service
spec:
  nodeSelector:
    kubernetes.io/hostname: {{ worker1 }}
  hostNetwork: true
  containers:
  - name: appcntr1
    image: {{ test_image }}
    command: ['/bin/sh', '-c', 'iperf3 -s']

