apiVersion: v1
kind: Pod
metadata:
  name: {{ pod_worker2 }}
  annotations:
    v1.multus-cni.io/default-network: accelerated
spec:
  nodeSelector:
    kubernetes.io/hostname: {{ worker2 }}
  containers:
  - name: appcntr
    image: {{ test_image }}
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
    resources:
      requests:
        {{ sriov_resource_name }}: '1'
      limits:
        {{ sriov_resource_name }}: '1'
