apiVersion: v1
kind: Pod
metadata:
  name: {{ host_network_pod_worker1 }}
spec:
  nodeSelector:
    kubernetes.io/hostname: {{ worker1 }}
  hostNetwork: true
  containers:
  - name: appcntr1
    image: {{ test_image }}
    command: ['/bin/sh', '-c', 'sleep infinity']

