apiVersion: v1
kind: Pod
metadata:
  name: {{ iperf3_service_pod }}
  labels:
    app: iperf3-pod-service
spec:
  nodeSelector:
    kubernetes.io/hostname: {{ worker1 }}
  containers:
  - name: appcntr
    image: {{ test_image }}
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-c', 'iperf3 -s']
