apiVersion: v1
kind: Pod
metadata:
  name: {{ pod_worker1 }}
spec:
  nodeSelector:
    kubernetes.io/hostname: {{ worker1 }}
  containers:
  - name: appcntr
    image: {{ test_image }}
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
